site_name: Paystack Documentation
site_description: paystack documentation
site_author: Gbenga Adeyi
site_url: https://github.com/gray-adeyi/paystack
theme:
  name: "material"
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: paystack-light
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: paystack-dark
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - navigation.sections
    - navigation.path
    - navigation.top
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/paystack.svg
  favicon: assets/paystack.svg
  language: en
repo_name: gray-adeyi/paystack
repo_url: https://github.com/gray-adeyi/paystack

plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css