[project]
name = "paystack"
version = "0.1.0"
description = "documentation for paystack"
authors = [{ name = "Gbenga Adeyi", email = "adeyigbenga005@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["mike>=2.1.3", "mkdocs-material>=9.5.34"]
